# CI pipeline for the develop branch: build + test, no NuGet publish.

version: 1.0.{build}-alpha
branches:
  only:
    - develop
image: Visual Studio 2022
configuration: Release
platform: Any CPU

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore src/Paillave.Etl.sln

build_script:
  - cmd: dotnet build src/Paillave.Etl.sln --configuration %CONFIGURATION% --no-restore -p:WarningLevel=0

test_script:
  - cmd: dotnet test src/Paillave.Etl.Tests/Paillave.Etl.Tests.csproj --configuration %CONFIGURATION% --no-build --logger "Appveyor"
