using Paillave.Etl.EntityFrameworkCore.Tests.Entities;
using Paillave.Etl.Reactive.Operators;

namespace Paillave.Etl.EntityFrameworkCore.Tests
{
    public class BulkSaveTests : SqlDatabaseTests
    {
        public BulkSaveTests(MsSqlDatabaseFixture fixture) : base(fixture)
        { }

        [Fact]
        public async Task GivenTable_WhenEfCoreSave_ThenItemSavedWithId()
        {
            // arange
            var executionOptions = new ExecutionOptions<int>
            {
                Resolver = new SimpleDependencyResolver()
                    .Register<DbContext>(Context)
            };

            var streamProcessRunner = StreamProcessRunner.Create((ISingleStream<int> configStream) => configStream
                .CrossApply("generate ids", i => Enumerable.Range(2, i))
                .EfCoreSave("insert", builder => builder.Entity(i => new Post()
                {
                    PostId = i,
                    Name = $"Post {i}",
                }).InsertOnly()), "GivenSqlServerDatabase_WhenEfCoreSaveWithIdentityInsert_ThenItemSavedWithAutoGeneratedId");


            // act
            await streamProcessRunner.ExecuteAsync(3, executionOptions);


            //assert
            var posts = await Context.Posts.ToListAsync();
            posts.Should().BeEquivalentTo(new[]
            {
                new Post() { PostId = 2, Name = "Post 2", },
                new Post() { PostId = 3, Name = "Post 3", },
                new Post() { PostId = 4, Name = "Post 4", }
            });
        }

        [Fact]
        public async Task GivenTableWithIdentityPrimaryKey_WhenEfCoreSave_ThenItemSavedWithId()
        {
            // arange
            var executionOptions = new ExecutionOptions<int>
            {
                Resolver = new SimpleDependencyResolver()
                    .Register<DbContext>(Context)
            };

            var streamProcessRunner = StreamProcessRunner.Create((ISingleStream<int> configStream) => configStream
                    .CrossApply("generate ids", i => Enumerable.Range(2, i))
                    .EfCoreSave("insert", builder => builder.Entity(i => new Blog()
                    {
                        BlogId = i,
                        Name = $"Blog {i}",
                    }).InsertOnly().WithIdentityInsert()), "GivenSqlServerDatabase_WhenEfCoreSaveWithIdentityInsert_ThenItemSavedWithOriginalId");


            // act
            await streamProcessRunner.ExecuteAsync(3, executionOptions);


            //assert
            var blogs = await Context.Blogs.ToListAsync();
            blogs.Should().BeEquivalentTo(new[]
                {
                    new Blog() { BlogId = 2, Name = "Blog 2", },
                    new Blog() { BlogId = 3, Name = "Blog 3", },
                    new Blog() { BlogId = 4, Name = "Blog 4", }
                });
        }
    }
}